### PR TITLE
Add initial Conflict of Interest Policy

### LINKED ISSUE #30: Draft Conflict of Interest Policy

### PR DESCRIPTION
**Pull request by dlindahl**
I based this copy off of an example from http://www.idealist.org/info/Nonprofits/Gov5 with the inclusion of ensuring that member organization leaders are also included in the Conflict of Interest policy. We'll likely want to ensure that they sign a document stating that they've read and agree to this policy.

This closes #30

### CODE REVIEW

**Comment by dlindahl** [comment]
Assigned to @roughani for further review

**Comment by roughani** [comment]
The policy proposed here is very short. It might suffice, but the IRS - although they don't require a COI policy - has published a model policy they recommend all orgs adopt:

https://github.com/techramento/techramento.github.io/wiki/IRS-Sample-Conflict-of-Interest-Policy

(source: https://www.irs.gov/pub/irs-pdf/i1023.pdf (see Appendix A, pg. 25))

**Comment by dlindahl** [comment]
@techramento/board needs to read the wiki entry for the policy and approve by the usual checkbox format and by commenting their official approval
- [x] @dlindahl
- [x] @rjulian 
- [x] @efletch 
- [x] @roughani

**Comment by dlindahl** [comment]
I updated this PR with the latest copy from the wiki entry. I only made a couple changes:
- Removed from Article III Section 3d:
  > The type and rule above prints on all proofs including departmental reproduction proofs. MUST be removed before printing.

because it made no sense and I did not see it in the IRS's copy. I think this was a weird copy/paste issue with the original PDF file.
- After ratification, we will need to draft and sign a letter saying that we have read, understand, and agree to this policy. Additionally, we need to do it each year (Article VI Section 1)
- We will need to "periodically" review our member orgs and meetup spaces to ensure that they conform to this policy (Article VII Section 1b)

Beyond that, it looks good to me

**Comment by roughani** [comment]
I, Ash Roughani, have a copy of the Conflict of Interest Policy, understand the Conflict of Interest Policy, agree to comply with the Conflict of Interest Policy, and understand that Techramento is a charitable organization and I must engage in activities that which accomplish one or more of our tax-exempt purposes.

**Comment by dlindahl** [comment]
I, Derek Lindahl, have a copy of the Conflict of Interest Policy, understand the Conflict of Interest Policy, agree to comply with the Conflict of Interest Policy, and understand that Techramento is a charitable organization and I must engage in activities that which accomplish one or more of our tax-exempt purposes.

**Comment by efletch** [comment]
I, Emma Fletcher, have a copy of the Conflict of Interest Policy, understand the Conflict of Interest Policy, agree to comply with the Conflict of Interest Policy, and understand that Techramento is a charitable organization and I must engage in activities that which accomplish one or more of our tax-exempt purposes.

**Comment by rjulian** [comment]
I, Richard Julian, have a copy of the Conflict of Interest Policy, understand the Conflict of Interest Policy, agree to comply with the Conflict of Interest Policy, and understand that Techramento is a charitable organization and I must engage in activities that which accomplish one or more of our tax-exempt purposes.

**Pull request merged**
