### PR TITLE
Adoption of bylaws

### PR DESCRIPTION
**Pull request by dlindahl**
I opted to break each change into a separate commit to ensure the recording of the reason for each change.

When you have reviewed these changes and consent to approve them, click the checkbox next to your name and leave a comment verbally indicating your consent.
- [x] @dlindahl
- [x] @rjulian 
- [x] @roughani 
- [x] @efletch

### CODE REVIEW

**Comment by rjulian** [comment]
I give you my consent for these here bylaws.

**Comment by roughani** [comment]
I hereby approve this enthralling read. Looks great on Pocket! 

> For purposes of this section a GitHub Issue created from a GitHub username on record in the official Techramento repository constitutes valid writing. The intent of this provision is to allow the board of directors to use GitHub to approve actions, as long as a quorum of board members gives consent.

:octocat: :sparkles: :sparkles: :sparkles:

**Comment by efletch** [comment]
I approve these here bylaws :)

**Comment by dlindahl** [comment]
I consent to these bylaws

:tada:

**Pull request merged**
